### ISSUE TITLE
Read parquet from Azure Gen2 storage is very slow

### ISSUE THREAD

**Issue by kcyea** [dask/adlfs#128]
Hi All,

I had been trying to use dask to read parquet file from Azure Gen2 storage in my local machine. However, I realized the performance is very slow. To read one parquet file around 298MB (with 3 columns selected), it took around 20 minutes to return the result. 

Do you have any idea on how to improve performance? Or this is some heat up time for dask before it start to read the file? Besides that, by selecting only 3 columns, it will not download the whole file from blob storage right?

Please find the following for the snippet of my code:

```python
storage_options = {"account_name": ACCOUNT_NAME, "account_key": ACCOUNT_KEY}

ddf = dd.read_parquet(
     "az://test_container/test.parquet/Date=2020-11-01",
     storage_options=storage_options,
     engine="pyarrow",
     columns=["ColA", "ColB", "ColC"],
     gather_statistics=False,
)
ddf = ddf.compute(scheduler="threads")

print(ddf .head(10))
```

**Environment**:

- Dask version: 2.5.2
- Python version: 3.7.4
- Pyarrow: 1.0.1
- Operating System: Windows 10
- Install method (conda, pip, source): pip

Appreciate your input. Thanks.

**Comment by hayesgb** [comment]
Your version of Dask is quite old, and as written you will only have a single worker.  Additionally, there’s no mention of your local bandwidth, which will limit throughput to your local machine.  

It may be easier to use adlfs to copy the file to your local machine then open with Dask.  Else suggest you look at the distributed Client, which will leverage all the available cores on your local machine.

**Comment by kcyea** [comment]
@hayesgb Thanks for you response. I just realized the version is old because previously I am installing using **pip install "dask[complete]"**, thought that would be the latest one. I had upgrade the version. 

I don't go with copy file to local machine because we got many big files in azure, I don't want to download it to local but instead of reading it directly with limited selected columns, thought that would speed up the performance. By the way, for distributed client to leverage on more cores of my machine, is it we only need to add in the distributed client as the following?

```
storage_options = {"account_name": ACCOUNT_NAME, "account_key": ACCOUNT_KEY}

client = Client(n_workers=1, threads_per_worker=4, memory_limit="16GB")
d = dask.delayed(
        dd.read_parquet(
            "az://test_container/test.parquet/Date=2020-11-01",
            storage_options=storage_options,
            engine="pyarrow",
            columns=["ColA", "ColB", "ColC"],
            gather_statistics=False,
        )
    )
    df = dask.compute(d)[0]
    print(df.head(10))
```

My local download bandwidth is around 35Mbps. Any other way to optimize the performance? Thanks.

**Comment by hayesgb** [comment]
Setting up your local distributed client will happen as follows, which will give you as many workers as you have cores, and each worker will get an equal share of your system memory.

```
client = Client()
 ddf = dd.read_parquet(
            "az://test_container/test.parquet/Date=2020-11-01",
            storage_options=storage_options,
            engine="pyarrow",
            columns=["ColA", "ColB", "ColC"],
    )
ddf["ColA", "ColB", "ColC"]] = ddf[["ColA", "ColB", "ColC"]].astype(<verify appropriate>) --> If these are strings set datatype as something else as appropriate, int if possible

# Can you filter rowgroups?
ddf = ddf.set_index("Date")
ddf = ddf[ddf.index > "SOMEDATE", :]
ddf = ddf[ddf['COLA'] == <SOME VALUE>]

df = ddf.persist()

```

Based on what you're described, the issue is that you're a) connecting to a single file, and b) calling .compute() early in the process.  For the purposes of file reading, you get 1 file per worker.

Dask operates in a lazy paradigm, which means if you run the code described above, it will return almost instantly.  Effectively, it checks to see if it can execute, and if so, returns control to the user, and adds that step to a task graph.  You can string several steps like this together and build a complex task graph before ever triggering execution.

Calling .compute() on a dataframe is a blocking operation (meaning everything else halts until that finishes), and returns an in-memory Pandas DataFrame.  Calling .persist() on a dataframe triggers execution and returns a Dask Dataframe on the cluster.

Calling .head() on a Dask Dataframe will give the first 5 rows of an operation as a Pandas DataFrame.  Its much faster than calling .compute(), and can help knowing what to do next.

Try to build the compute graph and hold off triggering execution as long as possible.

**Comment by kcyea** [comment]
Thanks @hayesgb for the clear explanation. Will try that out.

**Comment by kcyea** [comment]
@hayesgb I have another question that would like to ask you regarding the performance. For the below code, it can return result in around 30seconds. Under directory **Date=2020-11-01**, it only contains one parquet file.

`client = Client()
 ddf = dd.read_parquet(
            ["az://test_container/test.parquet/Date=2020-11-01"],
            storage_options=storage_options,
            engine="pyarrow",
            columns=["ColA", "ColB", "ColC"],
    )`

I had make some codes change as the following and re-try:

`client = Client()
 ddf = dd.read_parquet(
            ["az://test_container/test.parquet/Date=2020-11-01/*parquet"],
            storage_options=storage_options,
            engine="pyarrow",
            columns=["ColA", "ColB", "ColC"],
    )`

Under directory **Date=2020-11-01**, it still contains only one parquet file. But it took 3minutes++ to return the result. Is it Dask behave very slow when we use * (glob) in the path?
