### ISSUE TITLE
Buggy docker-compose setup

### ISSUE THREAD

**Issue by TomAugspurger** [dask/adlfs#13]
I think that right now, our `docker-compose` has a couple issues.

1. It's caching stuff for too long. A change in the local `adlfs` repo should cause a rebuild. Right now I don't think it does
2. Shutdown? Right now you have to `ctrl-c` to stop the azurite server. Don't know if we want that.

**Comment by hayesgb** [comment]
Currently using command-line (rather than docker-compose) locally and in `azure-pipelines` seems to work fine.  Agree it still requires `ctrl-c` to shutdown which is less than ideal.  @AlbertDeFusco proposed using `pytest-docker-compose`, but it is not currently listed as compatible with Python>3.6.

I will take a look at implementing using `pytest` and yielding a running docker container for test execution.

**Comment by hayesgb** [comment]
Closing, as docker setup for unit tests implemented as a pytest fixture.
