### ISSUE TITLE
Fix compatibility with azure-storage-blob>=12.4.0

### ISSUE THREAD

**Issue by raybellwaves** [dask/adlfs#86]
See https://github.com/dask/adlfs/issues/83

**Comment by hayesgb** [comment]
The import error observed is easily fixed by changing the import location of the BlobPrefix class, which was changed in azure-storage-blob in v12.4.0.  However, I'm now seeing errors when executing unit tests with azurite.  It appears a change in 12.4.0 has broken compatibility there.  It's been reported [here](https://github.com/Azure/azure-sdk-for-python/issues/11941), so I'll wait on a fix there before implementing.

**Comment by raybellwaves** [comment]
FYI
https://github.com/Azure/azure-sdk-for-python/issues/11941#issuecomment-680648992
 > Hi there,
The changes to fix this issue have been made and it will be available in our September release.
If this is an urgent issue or if there are any concerns, let me know!

**Comment by hayesgb** [comment]
Fixed with #99
